#是否显示错误编号，帮助开发更快速定位错误 true 显示 false 不显示
SHOW_MSGNO: true
##文件相关信息
F_0001: 文件夹不存在！请创建后调用！
F_0004: 文件不存在！请确认后执行！
F_0005: 文件不存在或已被删除请确认后执行！
F_0006: 该路径为文件夹路径,请输入文件路径！
F_0009: 打包源文件找不到！
F_0010: 您下载的并不是一个文件！
#文件夹相关信息
F_0002: 文件夹已存在！请更换别名！
F_0003: 文件夹不存在！请确认后执行！
F_0010: 您操作的并不是一个文件夹！
#DB信息
F_0007: 数据库错误！
F_0008: 没有找到可打包文件！
