##端口号
PORT: 3000
##是否允许跨域
ALLOW_ORIGIN: true 
## 文件间隔符
FILE_SPLIT: $@$
##项目名字前缀
NAME: /files-api
##文件传入路径
FILEPATH: D:/fileUpload/
#文件大小
FILESIZE: 1024000
#模式 master 在保存文件时自动创建文件夹 guest 在保存文件时不自动创建文件夹
PATTERN: master
##临时文件保存路径
TEMPORARY: temp039
## 拷贝频率CRON
COPYCRON: 30 * * * * * 
#OSS配置
region: oss-cn-hangzhou
accessKeyId: LTAI9IK4Il7RjnLH
accessKeySecret: FC1n9gDWtezMFcjBMa0qEczTDGHu8k
bucket: qq102
#线上路径
OSSFILEPATH: test
READMETEXT: 本微服务由小熊猫提供技术支持1020529941@qq.com

##DB
RDS_IP: 172.19.20.206
RDS_PWD: 123456
RDS_POT: 6379
## redis db选取
RD_DB_NO:
  FILE: 8 ## 文件存入 8