##端口号
PORT: 3000
##是否允许跨域
ALLOW_ORIGIN: true 
## 文件间隔符
FILE_SPLIT: $@$
##项目名字前缀
NAME: /files-api
##文件传入路径
FILEPATH: D:/fileUpload/
#文件大小
FILESIZE: 10240000
# 模式 master 在保存文件时自动创建文件夹 guest 在保存文件时不自动创建文件夹（暂时删除这个模式）
##PATTERN: master
##临时文件保存路径
TEMPORARY: temp039
## 拷贝频率CRON http://cron.qqe2.com/ 在线生成
COPYCRON: 0 * * * * ? 
## 是否开启自动备份 add 增量备份 keep 替换备份 默认是 替换备份
KEEPFLAG: false
#OSS配置
region: xxx
accessKeyId: xxx
accessKeySecret: xxx
bucket: qq102
#线上路径
OSSFILEPATH: test
READMETEXT: 本微服务由小熊猫提供技术支持1020529941@qq.com

##DB
RDS_IP: localhost
RDS_PWD: 123456
RDS_POT: 6379
## redis db选取
RD_DB_NO:
  FILE: 8 ## 文件存入 8
  MESSION: 9 ## 任务数据库
  MESSION_ITEM: 10 ## 任务项数据库
